// ── Data Jeux vidéo ──
const gamesData = [
  { title: "Little Nightmares", note: 5, cover: "games/ln1.jpg", link: "https://backloggd.com/games/little-nightmares/" },
  { title: "Little Nightmares II", note: 5, cover: "games/ln2.jpg", link: "https://backloggd.com/games/little-nightmares-ii/" },
  { title: "Plantera", note: 5, cover: "games/plantera1.jpg", link: "https://backloggd.com/games/plantera/" },
  { title: "Plantera 2: Golden Acorn", note: 5, cover: "games/plantera2.jpg", link: "https://backloggd.com/games/plantera-2-golden-acorn/" },
  { title: "Milk Outside a Bag of Milk Outside a Bag of Milk", note: 3.5, cover: "games/milk.jpg", link: "https://backloggd.com/games/milk-outside-a-bag-of-milk-outside-a-bag-of-milk/" },
  { title: "Milk Inside a Bag of Milk Inside a Bag of Milk", note: 3, cover: "games/milki.jpg", link: "https://backloggd.com/games/milk-inside-a-bag-of-milk-inside-a-bag-of-milk/" },
  { title: "Muck", note: 3, cover: "games/muck.jpg", link: "https://www.backloggd.com/game/muck/" },
  { title: "Crab Game", note: 3, cover: "games/crabgame.jpg", link: "https://www.backloggd.com/game/crab-game/" },
  { title: "Zup! X", note: 2, cover: "games/zupx.jpg", link: "https://backloggd.com/games/zup-x/" },
  { title: "Zup!", note: 2, cover: "games/zup.jpg", link: "https://backloggd.com/games/zup/" },
  { title: "Left 4 Dead 2", note: 2.5, cover: "games/l4d2.jpg", link: "https://www.backloggd.com/game/left-4-dead-2/" },
  { title: "Portal 2", note: null, cover: "games/portal2.jpg", link: "https://www.backloggd.com/game/portal-2/" },
  { title: "JQ: countries", note: 1, cover: "games/jqcountries.jpg", link: "https://backloggd.com/games/jq-countries/" },
  { title: "Znkl: 177", note: 1, cover: "games/znkl.jpg", link: "https://backloggd.com/games/znkl-177/" },
  { title: "Minecraft: Java Edition", note: 5, cover: "games/minecraft.jpg", link: "https://backloggd.com/games/minecraft-java-edition/" },
  { title: "Slay the Spire", note: 5, cover: "games/slaythespire.jpg", link: "https://www.backloggd.com/game/slay-the-spire/" },
  { title: "Kingdom: Classic", note: 5, cover: "games/kingdom.jpg", link: "https://backloggd.com/games/kingdom-classic--1/" },
  { title: "Tricky Towers", note: 5, cover: "games/trickytowers.jpg", link: "https://backloggd.com/games/tricky-towers/" },
  { title: "Click to Ten", note: 5, cover: "games/clicktoten.jpg", link: "https://backloggd.com/games/click-to-ten/" },
  { title: "FTL: Faster Than Light", note: 5, cover: "games/ftl.jpg", link: "https://backloggd.com/games/ftl-faster-than-light/" },
  { title: "The Binding of Isaac: Rebirth", note: 5, cover: "games/isaac.jpg", link: "https://backloggd.com/games/the-binding-of-isaac-rebirth/" },
  { title: "Mirror", note: 5, cover: "games/mirror.jpg", link: "https://backloggd.com/games/mirror/" },
  { title: "Shapez", note: 5, cover: "games/shapez.jpg", link: "https://backloggd.com/games/shapez/" },
  { title: "Terraria", note: 5, cover: "games/terraria.jpg", link: "https://backloggd.com/games/terraria/" },
  { title: "Vampire Survivors", note: 5, cover: "games/vampiresurvivors.jpg", link: "https://backloggd.com/games/vampire-survivors/" },
  { title: "Poco", note: 4, cover: "games/poco.jpg", link: "https://backloggd.com/games/poco/" },
  { title: "Forager", note: 4, cover: "games/forager.jpg", link: "https://backloggd.com/games/forager/" },
  { title: "Lethal Company", note: 4, cover: "games/lethalcompany.jpg", link: "https://backloggd.com/games/lethal-company/" },
  { title: "Unturned", note: 4, cover: "games/unturned.jpg", link: "https://backloggd.com/games/unturned--1/" },
  { title: "Outlast", note: 4, cover: "games/outlast.jpg", link: "https://backloggd.com/games/outlast/" },
  { title: "BattleBlock Theater", note: 3.5, cover: "games/battleblock.jpg", link: "https://backloggd.com/games/battleblock-theater/" },
  { title: "Wednesdays", note: 3, cover: "games/wednesdays.jpg", link: "https://backloggd.com/games/wednesdays/" },
  { title: "Zort", note: 3, cover: "games/zort.jpg", link: "https://backloggd.com/games/zort/" },
  { title: "Eco Hole", note: 3, cover: "games/ecohole.jpg", link: "https://backloggd.com/games/eco-hole/" },
  { title: "Refunct", note: 3, cover: "games/refunct.jpg", link: "https://backloggd.com/games/refunct/" },
  { title: "Creature Clicker: Capture, Train, Ascend!", note: 3, cover: "games/creatureclicker.jpg", link: "https://backloggd.com/games/creature-clicker-capture-train-ascend/" },
  { title: "Inland", note: 3, cover: "games/inland.jpg", link: "https://backloggd.com/games/inland/" },
  { title: "Little Girl On Earth Asking Why She Asking Why", note: 2.5, cover: "games/littlegirl.jpg", link: "https://backloggd.com/games/little-girl-on-earth-asking-why-she-asking-why/" },
  { title: "Bokura", note: 2.5, cover: "games/bokura.jpg", link: "https://backloggd.com/games/bokura/" },
  { title: "Slash It", note: 2.5, cover: "games/slashit.jpg", link: "https://backloggd.com/games/slash-it/" },
  { title: "Isle of Jura", note: 2.5, cover: "games/isleofjura.jpg", link: "https://backloggd.com/games/isle-of-jura/" },
  { title: "Chained Together", note: 2.5, cover: "games/chainedtogether.jpg", link: "https://backloggd.com/games/chained-together/" },
  { title: "Pet Lands", note: 1.5, cover: "games/petlands.jpg", link: "https://backloggd.com/games/pet-lands/" },
  { title: "Redactem", note: 1.5, cover: "games/redactem.jpg", link: "https://backloggd.com/games/redactem/" },
  { title: "Business Tour", note: 1, cover: "games/businesstour.jpg", link: "https://backloggd.com/games/business-tour/" },
  { title: "Anime girl or Bottle?", note: 1, cover: "games/animegirl.jpg", link: "https://backloggd.com/games/anime-girl-or-bottle/" },
  { title: "Away", note: 0.5, cover: "games/away.jpg", link: "https://backloggd.com/games/away/" },
  { title: "Inside the Backrooms", note: 0.5, cover: "games/backrooms.jpg", link: "https://backloggd.com/games/inside-the-backrooms/" },
  { title: "Spellstone", note: null, cover: "games/spellstone.jpg", link: "https://backloggd.com/games/spellstone/" },
  { title: "Reigns", note: null, cover: "games/reigns.jpg", link: "https://backloggd.com/games/reigns/" },
  { title: "Pacify", note: null, cover: "games/pacify.jpg", link: "https://backloggd.com/games/pacify/" },
  { title: "Fears to Fathom: Scratch Creek", note: 2, cover: "games/fearstofathom.jpg", link: "https://backloggd.com/games/fears-to-fathom-scratch-creek/" },
  { title: "nophenia", note: 4, cover: "games/nophenia.jpg", link: "https://backloggd.com/games/nophenia/" },
  { title: "Land of Ghosts", note: 4, cover: "games/landofghosts.jpg", link: "https://backloggd.com/games/land-of-ghosts/" }
];