// ── JOURNAL & CALENDRIER ──
const journalData = [
{ d: "2026-04-19", t: "livre", title: "Le Bouffon", img: "covers/lebouffon.jpg", note: "lu en entier" },
{ d: "2026-04-19", t: "film", title: "Sonatine - Mélodie mortelle", img: "films/sonatine.webp", note: "premier film du réal que je regarde" },
{ d: "2026-04-19", t: "anime", title: "Choro Mesu Days", img: "anime/choromesudays.jpg", note: "hentai, 1/?", blur: true, status: "en cours" },
{ d: "2026-04-20", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 3/12", status: "en cours" },
{ d: "2026-04-20", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 1/12", status: "en cours" },
{ d: "2026-04-21", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 2/12", status: "en cours" },
{ d: "2026-04-21", t: "anime", title: "Dead or Love", img: "anime/deadorlove.jpg", note: "music" },
{ d: "2026-04-22", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 3/12", status: "en cours" },
{ d: "2026-04-22", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "commencé le livre, 10 pages", status: "en cours" },
{ d: "2026-04-23", t: "musique", title: "Safety in the Sun", img: "music/safetyinthesun.webp", note: "Sea of Dreams est de loin le meilleur son" },
{ d: "2026-04-23", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1181/?", status: "en cours" },
{ d: "2026-04-23", t: "anime", title: "Oshikake! Bakunyuu Gal Harem Seikatsu", img: "anime/oshikake.jpg", note: "hentai, 2/?", blur: true, status: "en cours" },
{ d: "2026-04-23", t: "musique", title: "Half Blood (BloodLuxe)", img: "music/halfblood.webp", note: "Flashout Freestyle >" },
{ d: "2026-04-24", t: "anime", title: "Be My Star", img: "anime/bemystar.jpg", note: "music" },
{ d: "2026-04-24", t: "musique", title: "Tristesse Business : Saison 1", img: "music/tristessebusiness.webp", note: "réécoute" },
{ d: "2026-04-24", t: "musique", title: "YAMOTO", img: "music/yamoto.webp", note: "réécoute" },
{ d: "2026-04-25", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 1/13", status: "en cours" },
{ d: "2026-04-26", t: "musique", title: "Luv(sic) Hexalogy", img: "music/luvsichexalogy.webp", note: "réécoute" },
{ d: "2026-04-26", t: "anime", title: "You & Aizu", img: "anime/youaizu.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Hanaikada", img: "anime/hanaikada.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Dengeki", img: "anime/dengeki.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "HoYoHoYo ni Shite Ageru♪", img: "anime/hoyohoyo.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Cha Cha Cha feat. G-Dragon", img: "anime/chachacha.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Move On", img: "anime/moveon.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Kaze no Anthem", img: "anime/kazenoanthem.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Bakumei Diver!!!!", img: "anime/bakumeidriver.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Malhae Yes Or No", img: "anime/malhae.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Mouth Music feat. Takkyu Ishino, Shinco", img: "anime/mouthmusic.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Cupcake feat. punchnello", img: "anime/cupcake.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Seoul Phonk feat. Skyminhyuk", img: "anime/seoulphonk.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 4/12", status: "en cours" },
{ d: "2026-04-26", t: "musique", title: "Just Friends", img: "music/justfriends.webp", note: "réécoute" },
{ d: "2026-04-26", t: "anime", title: "Adrenaline (NO1 Ver.)", img: "anime/adrenaline.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Ichi Ni no San", img: "anime/ichininosan.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Judgement?", img: "anime/judgement.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Side Quest King (KISAI remix)", img: "anime/sidequestking.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 2-3/13", status: "en cours" },
{ d: "2026-04-27", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "lecture de 16 pages", status: "en cours" },
{ d: "2026-04-28", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 4-5/13", status: "en cours" },
{ d: "2026-04-28", t: "musique", title: "Kekra", img: "music/kekra.webp", note: "réécoute" },
{ d: "2026-04-28", t: "musique", title: "spleen. social club", img: "music/spleensocialclub.PNG", note: "première écoute" },
{ d: "2026-04-29", t: "musique", title: "Extasia", img: "music/extasia.webp", note: "première écoute" },
{ d: "2026-04-30", t: "anime", title: "Jyuugoya", img: "anime/jyuugoya.jpg", note: "music" },
{ d: "2026-04-30", t: "anime", title: "Fact Check (Bulgasaui) (2Spade Remix)", img: "anime/factcheck.jpg", note: "music" },
{ d: "2026-04-30", t: "anime", title: "Lazy River", img: "anime/lazyriver.jpg", note: "music" },
{ d: "2026-05-01", t: "musique", title: "Tamara", img: "music/tamara.webp", note: "première écoute" },
{ d: "2026-05-02", t: "anime", title: "Rave In My Ears", img: "anime/raveinmyears.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Lanternoid", img: "anime/lanternoid.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Kira", img: "anime/kira.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Mirai no Lemon Sour x Final Fantasy VII Rebirth CM", img: "anime/mirainolemon.jpg", note: "commercial" },
{ d: "2026-05-02", t: "anime", title: "Uta no Uta (2026)", img: "anime/utanouta2026.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Re:Prism", img: "anime/reprism.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Jujutsu Kaisen Modulo Saishuu Sankan Hatsubai Kinen Special PV", img: "anime/jujutsukaisenmodulo.jpg", note: "short" },
{ d: "2026-05-02", t: "anime", title: "Flipper (2026)", img: "anime/flipper2026.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Girl feat. kojikoji", img: "anime/girlfeatkoji.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Sumikko Style Cafe Base Rap Compilation", img: "anime/sumikko.jpg", note: "commercial" },
{ d: "2026-05-02", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 4/12", status: "en cours" },
{ d: "2026-05-02", t: "anime", title: "Bousai Keihatsu Douga", img: "anime/bousaikeihatsu.jpg", note: "short" },
{ d: "2026-05-02", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "70/126", status: "en cours" },
{ d: "2026-05-03", t: "anime", title: "Broots", img: "anime/broots.jpg", note: "short" },
{ d: "2026-05-03", t: "anime", title: "Eguo", img: "anime/eguo.jpg", note: "short" },
{ d: "2026-05-03", t: "série", title: "One Piece", img: "series/onepiecesaison2.jpg", note: "saison 2 - 4/8", status: "en cours" },
{ d: "2026-05-03", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 5/12", status: "en cours" },
{ d: "2026-05-04", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "100/126", status: "en cours" },
{ d: "2026-05-05", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "terminé" },
{ d: "2026-05-05", t: "anime", title: "Sigan Yeokhaeng", img: "anime/siganyeokhaeng.jpg", note: "music" },
{ d: "2026-05-05", t: "anime", title: "Dance at the Moonlight feat. kojikoji", img: "anime/danceatthemoonlight.jpg", note: "music" },
{ d: "2026-05-05", t: "anime", title: "Hoyahoyaraa", img: "anime/hoyahoyaraa.jpg", note: "music" },
{ d: "2026-05-06", t: "anime", title: "Toge", img: "anime/toge.jpg", note: "music" },
{ d: "2026-05-06", t: "anime", title: "Bakusoku Ronriness", img: "anime/bakusokuronriness.jpg", note: "music" },
{ d: "2026-05-06", t: "anime", title: "Mind Scape", img: "anime/mindscape.jpg", note: "short" },
{ d: "2026-05-06", t: "anime", title: "Madoromi no Shuumatsu", img: "anime/madorominoshuumatsu.jpg", note: "short" },
{ d: "2026-05-06", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 6/13", status: "en cours" },
{ d: "2026-05-07", t: "anime", title: "Mr. Shape", img: "anime/mrshape.jpg", note: "short episode, 4/4" },
{ d: "2026-05-07", t: "anime", title: "Parking Area", img: "anime/parkingarea.jpg", note: "short" },
{ d: "2026-05-08", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1182/?", status: "en cours" },
{ d: "2026-05-09", t: "anime", title: "Haru wo Irodoru", img: "anime/haruwoirodoru.jpg", note: "short" },
{ d: "2026-05-09", t: "anime", title: "Chichin Pui Pui", img: "anime/chichinpuipui.jpg", note: "music" },
{ d: "2026-05-09", t: "anime", title: "Chiikawa Park TV CMs", img: "anime/chiikawaparkcms.jpg", note: "commercial" },
{ d: "2026-05-09", t: "anime", title: "Hifukidake", img: "anime/hifukidake.jpg", note: "short" },
{ d: "2026-05-09", t: "anime", title: "Jiu Wo", img: "anime/jiuwo.jpg", note: "short" },
{ d: "2026-05-09", t: "anime", title: "Koi no Tamashii", img: "anime/koinotamashii.jpg", note: "music" },
{ d: "2026-05-09", t: "anime", title: "Star Trail", img: "anime/startrail.jpg", note: "music" },
{ d: "2026-05-09", t: "anime", title: "NaN Game", img: "anime/nangame.jpg", note: "music" },
{ d: "2026-05-10", t: "anime", title: "Kudamonou", img: "anime/kudamonou.jpg", note: "short episode, 3/3" },
{ d: "2026-05-10", t: "anime", title: "Sweet Singapore CMs", img: "anime/sweetsingaporecms.jpg", note: "commercial" },
{ d: "2026-05-10", t: "anime", title: "Poke Oki", img: "anime/pokeoki.jpg", note: "short" },
{ d: "2026-05-10", t: "anime", title: "Konohakaseki no Natsu", img: "anime/konohakaseki.jpg", note: "short film" },
{ d: "2026-05-10", t: "anime", title: "Kujira wo Yumemu", img: "anime/kujirawoyumeru.jpg", note: "short" },
{ d: "2026-05-10", t: "anime", title: "I Got feat. Woodie Gochild", img: "anime/igotwoodie.jpg", note: "music" },
{ d: "2026-05-10", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 6/12", status: "en cours" },
{ d: "2026-05-10", t: "anime", title: "Mangzhong", img: "anime/mangzhong.jpg", note: "short film" },
{ d: "2026-05-12", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 5/12", status: "en cours" },
{ d: "2026-05-12", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 7/13", status: "en cours" },
{ d: "2026-05-14", t: "anime", title: "Kin no Ono, Gin no Ono, Emerald no Ono", img: "anime/kinnoonogin.jpg", note: "music" },
{ d: "2026-05-14", t: "musique", title: "Circles", img: "music/circles.webp", note: "réécoute" },
{ d: "2026-05-15", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 6/12", status: "en cours" },
{ d: "2026-05-16", t: "musique", title: "Iceman", img: "music/iceman.webp", note: "première écoute, ennuyeux à mourir" },
{ d: "2026-05-16", t: "musique", title: "Maid of Honour", img: "music/maidofhonour.webp", note: "première écoute, nul" },
{ d: "2026-05-16", t: "musique", title: "Habibti", img: "music/habibti.webp", note: "première écoute, nul" },
{ d: "2026-05-16", t: "anime", title: "Kick-Heart", img: "anime/kick-heart.jpg", note: "short film" },
{ d: "2026-05-17", t: "film", title: "Junk Head", img: "films/junkhead.webp", note: "une vibe à la blame" },
{ d: "2026-05-17", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 7/12, l'anime est vraiment bien, top 3 persos : Yasuaki Kaku, Mitsuhide Ryuumon, Gou Sugou", status: "en cours" },
{ d: "2026-05-18", t: "manga", title: "Tower Dungeon", img: "manga/towerdungeon.jpg", note: "premier tome de lu, très bon début, j'adore l'ambiance", status: "en cours" },
{ d: "2026-05-18", t: "musique", title: "Pluie, montagnes et soleil", img: "music/pluiemontagnessoleil.webp", note: "première écoute même si je connaissais déjà quelques sons" },
{ d: "2026-05-18", t: "film", title: "Mad God", img: "films/madgod.webp", note: "fascinant" },
{ d: "2026-05-20", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 8/13", status: "en cours" },
{ d: "2026-05-21", t: "série", title: "One Piece", img: "series/onepiecesaison2.jpg", note: "saison 2 - 5/8", status: "en cours" },
{ d: "2026-05-21", t: "musique", title: "Balloonerism", img: "music/balloonerism.webp", note: "première écoute, album sympa, le meiller son est funny papers pour moi" },
{ d: "2026-05-21", t: "manga", title: "Tower Dungeon", img: "manga/towerdungeon.jpg", note: "second tome de lu", status: "en cours" },
{ d: "2026-05-21", t: "musique", title: "キャット", img: "music/キャット.webp", note: "première écoute" },
{ d: "2026-05-22", t: "anime", title: "Numb Numb feat. Hatsune Miku, Kasane Teto", img: "anime/numbnumb.jpg", note: "music" },
{ d: "2026-05-23", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1183/?", status: "en cours" },
{ d: "2026-05-23", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 1/24", status: "en cours" },
{ d: "2026-05-24", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 2-3-4/24", status: "en cours" },
{ d: "2026-05-24", t: "musique", title: "Ateyaba", img: "music/ateyaba.webp", note: "première écoute, je connaissais déjà Venus" },
{ d: "2026-05-24", t: "anime", title: "Bite (2024)", img: "anime/bite.jpg", note: "music" },
{ d: "2026-05-24", t: "anime", title: "Mofumofu Man", img: "anime/mofumofuman.jpg", note: "short" },
{ d: "2026-05-24", t: "anime", title: "Rakuraku Fukuyaku Jelly: Oshaberi na Ningen no Tame ni", img: "anime/rakurakufukuyaku.jpg", note: "commercial" },
{ d: "2026-05-24", t: "anime", title: "Tokyo Night Dreaming feat. No Rome", img: "anime/tokyonightdreaming.jpg", note: "music" },
{ d: "2026-05-24", t: "anime", title: "Expressions", img: "anime/expressions.jpg", note: "music" },
{ d: "2026-05-24", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 8/12", status: "en cours" },
{ d: "2026-05-24", t: "musique", title: "Keitaidenwa", img: "music/keitaidenwa.webp", note: "première écoute, je connaissais déjà Hyperventilation" },
{ d: "2026-05-24", t: "jeu", title: "Slime Rancher", img: "games/slimerancher.jpg", note: "94 minutes", status: "en cours" },
{ d: "2026-05-24", t: "anime", title: "Chimimonryou", img: "anime/chimimonryou.jpg", note: "hentai, 1/?", blur: true, status: "en cours" },
{ d: "2026-05-26", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 9/13", status: "en cours" },
{ d: "2026-05-27", t: "musique", title: "Brat", img: "music/brat.webp", note: "première écoute, je sors de ma zone de confort et c'est vraiment pas mal" },
{ d: "2026-05-27", t: "anime", title: "Airman ga Taosenai Team.Nekokan [Neko] Premium Version", img: "anime/airmangataosenai.jpg", note: "commercial" },
{ d: "2026-05-27", t: "jeu", title: "Slime Rancher", img: "games/slimerancher.jpg", note: "27 minutes", status: "en cours" },
{ d: "2026-05-27", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 5/24", status: "en cours" },
{ d: "2026-05-28", t: "film", title: "Cure", img: "films/cure.jpg", note: "pas convaincu" },
{ d: "2026-05-29", t: "livre", title: "Morphine", img: "covers/morphine.jpg", note: "lu dans le train vers Paris" },
{ d: "2026-05-30", t: "livre", title: "Le Nez", img: "covers/lenez.jpg", note: "lu dans le train vers Nice" },
{ d: "2026-05-31", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1184/?", status: "en cours" },
{ d: "2026-06-01", t: "musique", title: "Heroes & Villains", img: "music/heroesvillains.webp", note: "réécoute, un album toujours aussi exceptionnel" },
{ d: "2026-06-03", t: "musique", title: "Disco Inferno", img: "music/discoinferno.webp", note: "première écoute, bon petit délire, bonne vibe" },
{ d: "2026-06-03", t: "musique", title: "PUBLIC ENEMY", img: "music/publicenemy.jpg", note: "première écoute, ça s'écoute sans plus" },
{ d: "2026-06-03", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 9/12", status: "en cours" },
{ d: "2026-06-04", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 10/13", status: "en cours" },
{ d: "2026-06-04", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "1h30 à peu près sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-05", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 6-7/24", status: "en cours" },
{ d: "2026-06-06", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 8-9/24", status: "en cours" },
{ d: "2026-06-06", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "3h sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-07", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 10-16/24", status: "en cours" },
{ d: "2026-06-07", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "2h22 sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-08", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 17-19/24", status: "en cours" },
{ d: "2026-06-09", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 20-24/24" },
{ d: "2026-06-11", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 10/12", status: "en cours" },
{ d: "2026-06-12", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1185/?", status: "en cours" },
{ d: "2026-06-12", t: "anime", title: "Shinkirou", img: "anime/shinkirou.jpg", note: "music" },
{ d: "2026-06-13", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 11/13", status: "en cours" },
{ d: "2026-06-13", t: "musique", title: "Ivy League", img: "music/ivyleague.webp", note: "réécoute, les musiques ivy league et for what à jamais dans mon coeur..." },
{ d: "2026-06-13", t: "anime", title: "Bunch 25-shuunen Kinen Special PV: Gokushufudou", img: "anime/bunch25.jpg", note: "short" },
{ d: "2026-06-13", t: "anime", title: "Akane", img: "anime/akane.jpg", note: "music" },
{ d: "2026-06-13", t: "anime", title: "Torimodosou, Ichiban Taisetsu na Mono wo: GIST Project", img: "anime/torimodosou.jpg", note: "commercial" },
{ d: "2026-06-13", t: "anime", title: "Cin Sai Syu", img: "anime/cinsaisyu.jpg", note: "music" },
{ d: "2026-06-13", t: "anime", title: "No Thank Cute!", img: "anime/nothankcute.jpg", note: "music" },
{ d: "2026-06-13", t: "anime", title: "Vision Megane CMs", img: "anime/visionmegane.jpg", note: "commercial" },
{ d: "2026-06-13", t: "anime", title: "Mebae feat. Phoka", img: "anime/mebae.jpg", note: "music" },
{ d: "2026-06-13", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "2h18 sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-14", t: "jeu", title: "Fears to Fathom: Scratch Creek", img: "games/fearstofathom.jpg", note: "jeu terminé en 2,7 heures, en une session, pas convaincu" },
{ d: "2026-06-15", t: "anime", title: "Heart Mark Oome", img: "anime/heartmarkoome.jpg", note: "hentai, 2/?", blur: true, status: "en cours" },
{ d: "2026-06-16", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 12/13", status: "en cours" },
{ d: "2026-06-16", t: "anime", title: "Rocket Science", img: "anime/rocketscience.jpg", note: "music" },
{ d: "2026-06-16", t: "anime", title: "Petals", img: "anime/petals.jpg", note: "music" },
{ d: "2026-06-16", t: "anime", title: "Free To Go", img: "anime/freetogo.jpg", note: "music" },
{ d: "2026-06-16", t: "anime", title: "Aisarenakutemo Kimi ga Iru feat. Hatsune Miku", img: "anime/aisarenakutemo.jpg", note: "music" },
{ d: "2026-06-16", t: "anime", title: "Red Table", img: "anime/redtable.jpg", note: "short" },
{ d: "2026-06-17", t: "anime", title: "Desk Bugs", img: "anime/deskbugs.jpg", note: "short" },
{ d: "2026-06-17", t: "anime", title: "Lakenaria no Yume", img: "anime/lakenaria.jpg", note: "music" },
{ d: "2026-06-17", t: "anime", title: "Muu", img: "anime/muu.jpg", note: "music" },
{ d: "2026-06-17", t: "anime", title: "Tarepanda (ONA)", img: "anime/tarepanda.jpg", note: "short" },
{ d: "2026-06-17", t: "anime", title: "Chocopa", img: "anime/chocopa.jpg", note: "short" },
{ d: "2026-06-17", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "3h07 sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-18", t: "film", title: "Backrooms", img: "films/backrooms.jpg", note: "je l'ai regardé au cinéma, un peu déçu pour être honnête" },
{ d: "2026-06-19", t: "anime", title: "Reika wa Karei na Boku no Joou The Animation", img: "anime/reika.jpg", note: "hentai, 1/?", blur: true, status: "en cours" },
{ d: "2026-06-20", t: "anime", title: "Play", img: "anime/play.jpg", note: "music" },
{ d: "2026-06-21", t: "anime", title: "Kamisama Hajimemashita (Music)", img: "anime/kamisama.jpg", note: "music" },
{ d: "2026-06-21", t: "anime", title: "Himitsu Doushi", img: "anime/himitsudoushi.jpg", note: "short" },
{ d: "2026-06-21", t: "anime", title: "MAPPA 15th Anniversary Movie: Seikatsu", img: "anime/mappa15.jpg", note: "short" },
{ d: "2026-06-21", t: "manga", title: "Shouwaru Gal Shitsukerareru", img: "manga/shouwarugal.jpg", note: "hentai, 1/1", blur: true },
{ d: "2026-06-21", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 11-12/12, c'était vraiment bien" },
{ d: "2026-06-21", t: "musique", title: "HHHH²", img: "music/hhhh².jpg", note: "première écoute de ce projet surprise, pas nul mais pas exceptionnel non plus, j'ai connu mieux d'un Josman lover" },
{ d: "2026-06-22", t: "anime", title: "The Whole Blue World", img: "anime/wholeblue.jpg", note: "music" },
{ d: "2026-06-24", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 13/13" },
{ d: "2026-06-24", t: "anime", title: "Vinland Saga Season 2", img: "anime/vinlandsaga2.jpg", note: "normal episode, 2/24", status: "en cours" },
{ d: "2026-06-25", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "48 minutes sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-26", t: "film", title: "Prehistoric Beast", img: "films/prehistoricbeast.webp", note: "court-métrage sympa" },
{ d: "2026-06-27", t: "film", title: "MutantLand", img: "films/mutantland.jpg", note: "court-métrage aussi du même réal, en cgi cette fois mais toujours aussi cauchemardesque" },
{ d: "2026-06-27", t: "film", title: "D'une peinture... à l'autre", img: "films/peinturealautre.webp", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-06-27", t: "film", title: "Zig Zag", img: "films/zigzag.jpg", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-06-27", t: "film", title: "Le Vol d'Icare", img: "films/levoldicare.webp", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-06-27", t: "film", title: "Hors-jeu", img: "films/horsjeu.webp", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-06-27", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1186/?", status: "en cours" },
{ d: "2026-06-27", t: "anime", title: "Vinland Saga Season 2", img: "anime/vinlandsaga2.jpg", note: "normal episode, 1-4/24", status: "en cours" },
{ d: "2026-06-27", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "3h20 sur un serveur mmorpg, je suis passé niveau 40", status: "en cours" },
{ d: "2026-06-28", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "2h11 sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-28", t: "anime", title: "Massara", img: "anime/massara.jpg", note: "short" },
{ d: "2026-06-28", t: "anime", title: "Abyss in the World", img: "anime/abyssintheworld.jpg", note: "music" },
{ d: "2026-06-28", t: "anime", title: "Kishi Kaisen", img: "anime/kishikaisen.jpg", note: "music" },
{ d: "2026-06-28", t: "anime", title: "Roman Jet Charisma", img: "anime/romanjetcharisma.jpg", note: "music" },
{ d: "2026-06-28", t: "anime", title: "Poltergeist", img: "anime/poltergeist.jpg", note: "music" },
{ d: "2026-06-28", t: "anime", title: "Sakujitsu", img: "anime/sakujitsu.jpg", note: "music" },
{ d: "2026-06-28", t: "anime", title: "Vinland Saga Season 2", img: "anime/vinlandsaga2.jpg", note: "normal episode, 5-6/24", status: "en cours" },
{ d: "2026-06-29", t: "livre", title: "Schopenhauer", img: "covers/schopenhauer.jpg", note: "je commence la lecture du livre", status: "en cours" },
{ d: "2026-07-01", t: "livre", title: "Schopenhauer", img: "covers/schopenhauer.jpg", note: "continuation de la lecture", status: "en cours" },
{ d: "2026-07-01", t: "anime", title: "Homie's Tie!!", img: "anime/homiestie.jpg", note: "music" },
{ d: "2026-07-01", t: "anime", title: "Turn Around For Me", img: "anime/turnaroundforme.jpg", note: "music" },
{ d: "2026-07-01", t: "anime", title: "Imamura Shoken CMs", img: "anime/imamura.jpg", note: "commercial" },
{ d: "2026-07-01", t: "anime", title: "Gentle Teaching", img: "anime/gentleteaching.jpg", note: "music" },
{ d: "2026-07-01", t: "film", title: "Le Ravissement de Frank N. Stein", img: "films/ravissementfrank.jpg", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-07-02", t: "anime", title: "FBKingdom Story", img: "anime/fbkingdom.jpg", note: "short" },
{ d: "2026-07-02", t: "musique", title: "The Divine Feminine", img: "music/divinefeminine.webp", note: "première écoute même si je connaissais déjà quelques sons, vraiment pas mal, album très sensuel, il porte bien son titre" },
{ d: "2026-07-03", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1187/?", status: "en cours" },
{ d: "2026-07-03", t: "jeu", title: "nophenia", img: "games/nophenia.jpg", note: "fini en 3,1h réparties dans une journée, j'ai adoré" },
{ d: "2026-07-04", t: "anime", title: "Bimo Xinglu", img: "anime/bimoxinglu.jpg", note: "short" },
{ d: "2026-07-04", t: "musique", title: "Edward Risky", img: "music/edwardrisky.jpg", note: "première écoute, le retour de Krisy après 3ans sans album" },
{ d: "2026-07-04", t: "film", title: "78 Tours", img: "films/78tours.jpg", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-07-04", t: "film", title: "Nakounine", img: "films/nakounine.jpg", note: "court documentaire de Georges Schwizgebel" },
{ d: "2026-07-04", t: "film", title: "Le sujet du tableau", img: "films/lesujetdutableau.jpg", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-07-04", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "un petit retour sur valo parce que ça faisait longtemps histoire de (dernière game en octobre 2025)", status: "en cours" },
{ d: "2026-07-04", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "1h42", status: "en cours" },
{ d: "2026-07-05", t: "livre", title: "Schopenhauer", img: "covers/schopenhauer.jpg", note: "continuation de la lecture", status: "en cours" },
{ d: "2026-07-05", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "37 minutes pour reprendre des sensations", status: "en cours" },
{ d: "2026-07-06", t: "musique", title: "Paradis d'amour", img: "music/paradisdamour.webp", note: "réécoute, j'ai eu envie de le réécouter après la sortie de son dernier album, que de nostalgie et ça a plutôt bien vieilli" },
{ d: "2026-07-06", t: "musique", title: "Euphoria", img: "music/euphoria.webp", note: "réécoute" },
{ d: "2026-07-06", t: "film", title: "La Course à l'abîme", img: "films/lacoursealabime.jpg", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-07-07", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "petite session où j'ai battu mom's heart", status: "en cours" },
{ d: "2026-07-08", t: "anime", title: "One Piece: Heroines", img: "anime/onepieceheroines.jpg", note: "normal episode, 1/1, très mignon" },
{ d: "2026-07-09", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1188/?", status: "en cours" },
{ d: "2026-07-09", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "session nulle, je me suis fait déchier en boucle", status: "en cours" },
{ d: "2026-07-10", t: "anime", title: "Yani Neko", img: "anime/yanineko.jpg", note: "normal episode, 1/?, au vu d'à quel point c'est déjanté, soit je vais adorer soit je vais détester, on verra bien", status: "en cours" },
{ d: "2026-07-10", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "training", status: "en cours" },
{ d: "2026-07-11", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "training", status: "en cours" },
{ d: "2026-07-11", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "mom's heart battu une deuxième fois avec isaac", status: "en cours" },
{ d: "2026-07-11", t: "musique", title: "cats in the cold", img: "music/catsinthecold.webp", note: "première écoute, un bon album à écouter pour être encore plus déprimé" },
{ d: "2026-07-11", t: "anime", title: "Yani Neko", img: "anime/yanineko.jpg", note: "normal episode, 2/?", status: "en cours" },
{ d: "2026-07-11", t: "livre", title: "Schopenhauer", img: "covers/schopenhauer.jpg", note: "continuation de la lecture", status: "en cours" },
{ d: "2026-07-12", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "mom's heart battu une troisième fois avec isaac", status: "en cours" },
{ d: "2026-07-12", t: "livre", title: "Schopenhauer", img: "covers/schopenhauer.jpg", note: "continuation de la lecture", status: "en cours" },
{ d: "2026-07-13", t: "anime", title: "Dottabatta Chin Douchuu!", img: "anime/dottabatta.jpg", note: "music" },
{ d: "2026-07-13", t: "anime", title: "#Mugen ni Tomaranai", img: "anime/mugennitomaranai.jpg", note: "commercial" },
{ d: "2026-07-13", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "que des runs de merde", status: "en cours" },
{ d: "2026-07-13", t: "anime", title: "Mob Psycho 100: 10-shuunen Kinen Tokubetsu Eizou", img: "anime/mobpsycho10010.jpg", note: "short" },
{ d: "2026-07-13", t: "film", title: "Time and Tide", img: "films/timeandtide.webp", note: "vraiment très bonne découverte, ça partait dans tous les sens" },
{ d: "2026-07-13", t: "musique", title: "Whole Lotta Red", img: "music/wholelottared.webp", note: "réécoute" },
{ d: "2026-07-14", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "mom's heart battu une quatrième fois avec isaac, ça a l'air de m'avoir débloqué la suite (en plus d'une nouvelle voie qui descend dans la devil's room)", status: "en cours" },
{ d: "2026-07-14", t: "anime", title: "Satori", img: "anime/satori.jpg", note: "music" },
{ d: "2026-07-14", t: "anime", title: "Kidou Butouden G Gundam: 30-shuunen Kinen Fighting Movie", img: "anime/kidoubutouden.jpg", note: "short" },
{ d: "2026-07-14", t: "anime", title: "Omstart", img: "anime/omstart.jpg", note: "music" },
{ d: "2026-07-14", t: "anime", title: "Ichijiku Kemuri", img: "anime/ichijikukemuri.jpg", note: "music" },
{ d: "2026-07-14", t: "anime", title: "'Arirang' Animation Trailer: What Is Your Love Song?", img: "anime/bts.jpg", note: "short" },
{ d: "2026-07-14", t: "anime", title: "Sayonara Penguin", img: "anime/sayonarapenguin.jpg", note: "music" },
{ d: "2026-07-14", t: "anime", title: "Orion", img: "anime/orion.jpg", note: "music" },
{ d: "2026-07-14", t: "anime", title: "Fengwu You Shijie", img: "anime/fengwu.jpg", note: "short" },
{ d: "2026-07-14", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "une seule très bonne run de faite où j'ai battu satan", status: "en cours" },
{ d: "2026-07-14", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "training, monstrueux", status: "en cours" },
{ d: "2026-07-15", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "j'ai fait deux runs de dingue et les deux je suis mort dans des rooms de dingue, je n'ai jamais vu ça, même quand j'ai de la chance sur les items je finis par tomber sur les pires rooms", status: "en cours" },
{ d: "2026-07-15", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "mom's heart battu une cinquième fois avec isaac, de ce que j'ai compris je dois la battre onze fois, plus que six", status: "en cours" },
{ d: "2026-07-16", t: "musique", title: "The Real Me", img: "music/therealme.webp", note: "première écoute, nul dans l'ensemble avec deux trois fulgurances" },
{ d: "2026-07-16", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "que des runs de merde", status: "en cours" },
{ d: "2026-07-17", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "deux runs, une où je suis mort et une autre où j'ai encore tué mom", status: "en cours" },
{ d: "2026-07-17", t: "musique", title: "Nevermind", img: "music/nevermind.webp", note: "première vraie écoute, je me suis fait chier comme pas possible, aucune connexion esthétique avec l'album, je ne suis pas rentré dedans. Au mieux il y a deux sons que j'ai bien aimé et c'est les deux plus connus, à raison" },
{ d: "2026-07-17", t: "anime", title: "Karasu (PV)", img: "anime/karasu.jpg", note: "short" },
{ d: "2026-07-17", t: "anime", title: "Melodrama", img: "anime/melodrama.jpg", note: "music" },
{ d: "2026-07-17", t: "anime", title: "Ya Ya Ya", img: "anime/yayaya.jpg", note: "music" },
{ d: "2026-07-18", t: "anime", title: "009 Re:Cyborg x Zip", img: "anime/cyborgzip.jpg", note: "commercial" },
{ d: "2026-07-18", t: "anime", title: "PetitCure: Gekijou Manner Movie", img: "anime/petitcure.jpg", note: "short" },
{ d: "2026-07-18", t: "anime", title: "PUBG Mobile x Naruto: Shippuuden Collab", img: "anime/narutopubg.jpg", note: "short" },
{ d: "2026-07-18", t: "anime", title: "5-56 Hokuto no Ken: Akanai Tobira-hen", img: "anime/556.jpg", note: "commercial" },
{ d: "2026-07-18", t: "anime", title: "Aloha You: Kizuna", img: "anime/alohayou.jpg", note: "music" },
{ d: "2026-07-18", t: "anime", title: "Ama Gli Animali", img: "anime/amagli.jpg", note: "short" },
{ d: "2026-07-18", t: "film", title: "L'Odyssée", img: "films/odyssee.webp", note: "vu au cinéma, excellent, je n'ai pas vu le temps passer malgré le film de 3 heures" },
{ d: "2026-07-18", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "training", status: "en cours" },
{ d: "2026-07-19", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "mom battu 8 fois en tout, plus que 3", status: "en cours" },
{ d: "2026-07-19", t: "livre", title: "Schopenhauer", img: "covers/schopenhauer.jpg", note: "fini, c'était très enrichissant" },
{ d: "2026-07-19", t: "musique", title: "Charm", img: "music/charm.webp", note: "réécoute, c'est mignon sans plus, hormis Juna que je mets à des sphères au dessus du reste, reste qui est loin d'être nul pour autant, je tiens à le préciser" },
{ d: "2026-07-21", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "training", status: "en cours" },
{ d: "2026-07-22", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "reprise des ranked, j'ai été placé plat 2, plus qu'à reprendre l'habitude", status: "en cours" },
{ d: "2026-07-23", t: "anime", title: "KFC x Yuanshen Liandong PV: Qiji Shunjian Meiwei Zaixian", img: "anime/kfc.jpg", note: "commercial" },
{ d: "2026-07-23", t: "anime", title: "Box Party", img: "anime/boxparty.jpg", note: "short" },
{ d: "2026-07-23", t: "anime", title: "Fade into Blue", img: "anime/fadeintoblue.jpg", note: "music" },
{ d: "2026-07-23", t: "anime", title: "Benghuai: Xing Qiong Tiedao - San Zhounian Zhutiqu: Tiansheng Guicai", img: "anime/zhutiqu.jpg", note: "music" },
{ d: "2026-07-23", t: "musique", title: "Minecraft: Volume Alpha", img: "music/minecraft.webp", note: "réécoute, que d'émotions... ça me rend si nostalgique" },
{ d: "2026-07-23", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "je me fais défoncer", status: "en cours" },
{ d: "2026-07-24", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "je me fais défoncer", status: "en cours" },
{ d: "2026-07-24", t: "anime", title: "Tsunaide", img: "anime/tsunaide.jpg", note: "short, c'est vraiment mignon" },
{ d: "2026-07-24", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1189/?", status: "en cours" },
{ d: "2026-07-25", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "nul", status: "en cours" },
{ d: "2026-07-25", t: "film", title: "Plastic Tears", img: "films/plastictears.jpg", note: "court-métrage de Jun Miyazaki, j'en pense rien, c'était très spécial" },
{ d: "2026-07-26", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "abominable", status: "en cours" },
{ d: "2026-07-26", t: "film", title: "Rapid Fire", img: "films/rapidfire.webp", note: "court-métrage de Jun Miyazaki, j'en pense rien, c'était très spécial" },
{ d: "2026-07-26", t: "film", title: "Flip Light Cruiser", img: "films/fliplightcruiser.jpg", note: "court-métrage de Jun Miyazaki, j'en pense rien, c'était très spécial" },
{ d: "2026-07-26", t: "anime", title: "Sunny (Music, 2026)", img: "anime/sunny.jpg", note: "music" },
{ d: "2026-07-26", t: "anime", title: "Hatachi no Kenketsu CMs", img: "anime/hatachinokenketsu.jpg", note: "commercial, la première pub est sortie en 2024 et la deuxième en 2026" },
{ d: "2026-07-26", t: "anime", title: "Disney Twisted-Wonderland CMs", img: "anime/disney.jpg", note: "commercial, il y a eu des ajouts depuis 2024" },
{ d: "2026-07-26", t: "anime", title: "Why Häagen-Dazs?", img: "anime/dazs.jpg", note: "commercial" },
{ d: "2026-07-26", t: "anime", title: "Yuanshen: Rui Shou Xiang Wen", img: "anime/yuanshenrui.jpg", note: "commercial" },
{ d: "2026-07-26", t: "anime", title: "Yuanshen: Wu Zhounian Zhutiqu - Huijia de Lu", img: "anime/yuanshenwu.jpg", note: "commercial" },
{ d: "2026-07-26", t: "musique", title: "Graduation", img: "music/graduation.webp", note: "première réelle écoute même si je connaissais la majorité des tracks, excellent, rien à dire de plus" },
{ d: "2026-07-26", t: "anime", title: "Yani Neko", img: "anime/yanineko.jpg", note: "normal episode, 3/?", status: "en cours" },
{ d: "2026-07-26", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "3h sur isaac, j'ai battu mom 11 fois puis une douzième qui m'a permis d'accéder à la cathédrale pour la première fois et j'ai battu isaac, c'était une session azazel pour changer un peu et c'était vraiment fun, j'ai perdu une seule run au début et après j'ai enchaîné que des wins", status: "en cours" },
{ d: "2026-07-26", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "+9rr", status: "en cours" },
{ d: "2026-07-26", t: "jeu", title: "Counter-Strike 2", img: "games/cs2.jpg", note: "reprise, c'était sympathique", status: "en cours" },
{ d: "2026-07-27", t: "livre", title: "La Mort d' Ivan Illitch / Maitre et Serviteur / Trois Morts", img: "covers/illitch.jpg", note: "commencement de la lecture" },
{ d: "2026-07-27", t: "musique", title: "DOPAMINE", img: "music/dopamine.webp", note: "réécoute, c'est légèrement au dessus de la moyenne sans plus, quelques sons au dessus du lot" },
{ d: "2026-07-27", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "j'ai essayé le bébé bleu pour tenter de battre isaac et débloquer le dé mais je me suis fait défoncer comme pas possible, ça va être compliqué", status: "en cours" },
{ d: "2026-07-27", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "nul", status: "en cours" },
{ d: "2026-07-28", t: "musique", title: "Yuri", img: "music/yuri.webp", note: "première réelle écoute même si je connaissais quelques tracks, on est là sur un haut niveau de rap" },
{ d: "2026-07-28", t: "livre", title: "La Mort d' Ivan Illitch / Maitre et Serviteur / Trois Morts", img: "covers/illitch.jpg", note: "poursuite de la lecture" },
{ d: "2026-07-29", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "1 win, 2 lose", status: "en cours" },
{ d: "2026-07-29", t: "jeu", title: "Counter-Strike 2", img: "games/cs2.jpg", note: "une game sur dust 2, win", status: "en cours" },
{ d: "2026-07-29", t: "musique", title: "Vréel 3", img: "music/vréel3.webp", note: "première réelle écoute même si je connaissais quelques tracks, c'est pas mal" },
{ d: "2026-07-29", t: "musique", title: "Stratos", img: "music/stratos.webp", note: "réécoute, assez moyen, l'album galère à démarrer et même une fois lancé on finit par retomber dans le moyen, le seul son qui m'a fait vibre c'est Vibe & Sun" },
{ d: "2026-07-30", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "1 win, 1 lose", status: "en cours" },
{ d: "2026-07-30", t: "musique", title: "1994", img: "music/1994.webp", note: "réécoute" },
{ d: "2026-07-30", t: "musique", title: "Jazz Samba Encore!", img: "music/jazzsambaencore.webp", note: "première écoute, je connaissais déjà cet artiste légendaire bien évidemment, j'ai le vinyle de Getz/Gilberto, excellent album" },
{ d: "2026-07-31", t: "musique", title: "Radio Suicide", img: "music/radiosuicide.webp", note: "première vraie écoute, pas ultra convaincu" },
{ d: "2026-08-01", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "4w/2l, j'ai fait de très bonnes games, les réflexes commencent à revenir et je suis enfin monté D1 !", status: "en cours" },
{ d: "2026-08-01", t: "film", title: "Hana-bi", img: "films/hana-bi.webp", note: "deuxième film de kitano que je regarde et il est exceptionnel, c'est le meilleur film que j'ai regardé de ma vie" },
{ d: "2026-08-01", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "j'ai été médiocre avec azazel c'est dire mon niveau, trop impatient", status: "en cours" },
{ d: "2026-08-02", t: "film", title: "Jamila's Mirror", img: "films/jamilasmirror.png", note: "documentaire, 🇵🇸" },
{ d: "2026-08-02", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "que des games de merde", status: "en cours" },
{ d: "2026-08-02", t: "musique", title: "Reaching for a Star", img: "music/rfas.webp", note: "réécoute" },
{ d: "2026-08-02", t: "anime", title: "I-Bull", img: "anime/i-bull.jpg", note: "music" },
{ d: "2026-08-02", t: "anime", title: "Engawa de Dancehall", img: "anime/engawa.jpg", note: "music" },
{ d: "2026-08-02", t: "anime", title: "Soko ga Hen da yo! Inuneko Saiban", img: "anime/sokoga.jpg", note: "commercial" },
{ d: "2026-08-02", t: "anime", title: "Yahoo! Japan 23rd Anniversary: Arigatou no Kiseki", img: "anime/yahoo.jpg", note: "commercial" },
{ d: "2026-08-02", t: "anime", title: "BooooM!!!", img: "anime/boooom.jpg", note: "music" },
{ d: "2026-08-02", t: "anime", title: "Kuraiai", img: "anime/kuraiai.jpg", note: "music" },
{ d: "2026-08-02", t: "anime", title: "Rasen", img: "anime/rasen.jpg", note: "music" },
{ d: "2026-08-02", t: "anime", title: "Yani Neko", img: "anime/yanineko.jpg", note: "normal episode, 4-5/?", status: "en cours" },
{ d: "2026-08-02", t: "livre", title: "La Mort d' Ivan Illitch / Maitre et Serviteur / Trois Morts", img: "covers/illitch.jpg", note: "poursuite de la lecture" },
{ d: "2026-08-03", t: "musique", title: "Star-Crossed", img: "music/starcrossed.webp", note: "réécoute" },
{ d: "2026-08-03", t: "musique", title: "A Great Chaos", img: "music/agreatchaos.webp", note: "réécoute" },
{ d: "2026-08-03", t: "musique", title: "Camera Roll", img: "music/cameraroll.webp", note: "réécoute" },
{ d: "2026-08-03", t: "musique", title: "Neon Tokyo // ?????", img: "music/neontokyo.webp", note: "première écoute, single" },
{ d: "2026-08-03", t: "musique", title: "i'm closing my eyes", img: "music/imclosingeyes.webp", note: "première écoute, single" },
{ d: "2026-08-03", t: "musique", title: "[oops]", img: "music/oops.webp", note: "première écoute, single" },
{ d: "2026-08-03", t: "musique", title: "another.wun", img: "music/anotherwun.webp", note: "première écoute, single" },
{ d: "2026-08-03", t: "musique", title: "moonglow", img: "music/moonglow.webp", note: "réécoute, single" },
{ d: "2026-08-03", t: "musique", title: "breakfast", img: "music/breakfast.webp", note: "réécoute, single" },
{ d: "2026-08-03", t: "musique", title: "homeshook", img: "music/homeshook.webp", note: "première écoute, single" },
{ d: "2026-08-03", t: "musique", title: "fall apart", img: "music/fallapart.webp", note: "réécoute, single" },
{ d: "2026-08-03", t: "musique", title: "It's Raining", img: "music/raining.webp", note: "réécoute, single" },
{ d: "2026-08-03", t: "musique", title: "drive by", img: "music/driveby.webp", note: "réécoute, single" },
{ d: "2026-08-03", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "...", status: "en cours" },
{ d: "2026-08-04", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "...", status: "en cours" },
{ d: "2026-08-04", t: "musique", title: "runaway", img: "music/runaway.webp", note: "réécoute, single" },
{ d: "2026-08-04", t: "musique", title: "sidewalk safari", img: "music/sidewalksafari.webp", note: "réécoute, ep" },
{ d: "2026-08-04", t: "musique", title: "Reflection", img: "music/reflection.webp", note: "première écoute, single" },
{ d: "2026-08-04", t: "musique", title: "Haunt Me", img: "music/hauntme.webp", note: "réécoute, single" },
{ d: "2026-08-04", t: "musique", title: "i'll be okay", img: "music/illbeokay.webp", note: "réécoute, single" },
{ d: "2026-08-04", t: "musique", title: "Fallen", img: "music/fallen.webp", note: "réécoute, single" },
{ d: "2026-08-04", t: "musique", title: "me when i watch bluey", img: "music/bluey.webp", note: "première écoute, ep" },
{ d: "2026-08-04", t: "musique", title: "make you feel", img: "music/makeyoufeel.webp", note: "première écoute, single" },
{ d: "2026-08-04", t: "musique", title: "have u seen my dog", img: "music/haveuseenmydog.webp", note: "première écoute, single" },
{ d: "2026-08-04", t: "musique", title: "lovesick", img: "music/lovesick.webp", note: "réécoute, single" },
{ d: "2026-08-04", t: "livre", title: "La Mort d' Ivan Illitch / Maitre et Serviteur / Trois Morts", img: "covers/illitch.jpg", note: "poursuite de la lecture au taf" },
{ d: "2026-08-04", t: "musique", title: "Silent Dialogue", img: "music/silentdialogue.webp", note: "première écoute, je ne connaissais pas du tout, la genèse de potsu, c'est ok sans plus" },
{ d: "2026-08-04", t: "musique", title: "Cat Naps", img: "music/catnaps.webp", note: "première écoute, je ne connaissais pas non plus, pas mal du tout" },
{ d: "2026-08-04", t: "musique", title: "Moon Beams", img: "music/moonbeams.webp", note: "première écoute" },
{ d: "2026-08-05", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "de la merde", status: "en cours" },
{ d: "2026-08-05", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "premier challenge réussi", status: "en cours" },
{ d: "2026-08-05", t: "musique", title: "000$", img: "music/000$.webp", note: "réécoute" },
{ d: "2026-08-05", t: "musique", title: "J.O.$", img: "music/J.O.$.webp", note: "réécoute" },
{ d: "2026-08-05", t: "livre", title: "La Mort d' Ivan Illitch / Maitre et Serviteur / Trois Morts", img: "covers/illitch.jpg", note: "poursuite de la lecture" },
{ d: "2026-08-06", t: "musique", title: "M.A.N (Black Roses & Lost Feelings)", img: "music/M.A.N.webp", note: "réécoute" },
{ d: "2026-08-06", t: "livre", title: "La Mort d' Ivan Illitch / Maitre et Serviteur / Trois Morts", img: "covers/illitch.jpg", note: "poursuite de la lecture" },
{ d: "2026-08-06", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1190/?", status: "en cours" },
{ d: "2026-08-07", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "je suis monté D2", status: "en cours" },
{ d: "2026-08-07", t: "musique", title: "The Great Impersonator", img: "music/greatimpersonator.webp", note: "première écoute et découverte de l'artiste, c'était nul à chier" },
{ d: "2026-08-08", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "3W/1L", status: "en cours" },
{ d: "2026-08-08", t: "anime", title: "Yani Neko", img: "anime/yanineko.jpg", note: "normal episode, 6/?", status: "en cours" },
{ d: "2026-08-09", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "meh", status: "en cours" },
{ d: "2026-08-09", t: "anime", title: "Daisan Wakusei", img: "anime/daisanwakusei.jpg", note: "music" },
{ d: "2026-08-09", t: "anime", title: "Jaken GALDVAZAAG", img: "anime/jaken.jpg", note: "music" },
{ d: "2026-08-09", t: "anime", title: "Nya Nya Nya Chu Nya (NNNCN)", img: "anime/nya.jpg", note: "music" },
{ d: "2026-08-09", t: "anime", title: "2002", img: "anime/2002.jpg", note: "music" },
{ d: "2026-08-09", t: "livre", title: "La Mort d' Ivan Illitch / Maitre et Serviteur / Trois Morts", img: "covers/illitch.jpg", note: "livre terminé" },
{ d: "2026-08-09", t: "musique", title: "The Melodic Blue", img: "music/themelodicblue.webp", note: "première écoute même si je connaissais les tracks les plus connues, l'album est assez médiocre" },
{ d: "2026-08-09", t: "film", title: "Il était une fois Koziavine", img: "films/koziavine.jpg", note: "court-métrage de Andreï Khrjanovski, exceptionnel" },
{ d: "2026-08-09", t: "anime", title: "Nuki Nuki Zupposism", img: "anime/zupposism.jpg", note: "hentai, 1/?", blur: true, status: "en cours" },
{ d: "2026-08-09", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "3 runs avec eden, je me suis fait niquer sur les trois", status: "en cours" },
{ d: "2026-08-09", t: "anime", title: "We Will Rise Again", img: "anime/riseagain.jpg", note: "music" },
{ d: "2026-08-09", t: "anime", title: "Re,bloom*", img: "anime/rebloom.jpg", note: "music" },
{ d: "2026-08-09", t: "anime", title: "Astral Lamp", img: "anime/astrallamp.jpg", note: "music" },
{ d: "2026-08-09", t: "anime", title: "Lovin'♡Rabbit", img: "anime/lovinrabbit.jpg", note: "music" },
{ d: "2026-08-09", t: "anime", title: "Oneul-man-eun", img: "anime/oneul.jpg", note: "music" },
{ d: "2026-08-09", t: "anime", title: "One Glowing Heart", img: "anime/oneglowingheart.jpg", note: "music" },
{ d: "2026-08-10", t: "livre", title: "Marche ou crève", img: "covers/marcheoucreve.jpg", note: "j'ai recommencé le bouquin après l'avoir abandonné fut un temps", status: "en cours" },
{ d: "2026-08-11", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "1W/1L", status: "en cours" },
{ d: "2026-08-11", t: "musique", title: "I Lay Down My Life for You", img: "music/ilaydown.webp", note: "première écoute" },
{ d: "2026-08-12", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "unrated chill", status: "en cours" },
{ d: "2026-08-12", t: "film", title: "Le Mystère Koumiko", img: "films/koumiko.webp", note: "documentaire, je ne sais pas quoi en penser" },
{ d: "2026-08-13", t: "film", title: "Kak stat chelovekom", img: "films/chelovekom.webp", note: "court-métrage, que dire" },
{ d: "2026-08-14", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "3W, je suis monté D3", status: "en cours" },
{ d: "2026-08-15", t: "musique", title: "Mula", img: "music/mula.webp", note: "réécoute, un classique" },
{ d: "2026-08-15", t: "musique", title: "In Rainbows", img: "music/inrainbows.webp", note: "première écoute" },
{ d: "2026-08-16", t: "film", title: "La Brûlure de mille soleils", img: "films/millesoleils.png", note: "court-métrage" },
{ d: "2026-08-16", t: "anime", title: "Senritsu", img: "anime/senritsu.jpg", note: "short" },
{ d: "2026-08-16", t: "anime", title: "Psychomagic In An Adobe Home", img: "anime/psychomagic.jpg", note: "music" },
{ d: "2026-08-16", t: "anime", title: "Pluggin' Away", img: "anime/pluggin.jpg", note: "music" },
{ d: "2026-08-16", t: "anime", title: "Tsuzuku Tousou", img: "anime/tsuzuku.jpg", note: "music" },
{ d: "2026-08-16", t: "anime", title: "Contemporary Dance", img: "anime/contemporary.jpg", note: "music" },
{ d: "2026-08-16", t: "anime", title: "Umya Unya Happy Life", img: "anime/umya.jpg", note: "music" },
{ d: "2026-08-16", t: "anime", title: "Houkiboshi (2026)", img: "anime/houkiboshi.jpg", note: "music" },
{ d: "2026-08-16", t: "anime", title: "Fleur The Animation", img: "anime/fleur.jpg", note: "hentai, 2/2", blur: true },
{ d: "2026-08-16", t: "livre", title: "Marche ou crève", img: "covers/marcheoucreve.jpg", note: "poursuite de la lecture", status: "en cours" },
{ d: "2026-08-16", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "que des runs de merde avec blue baby, décidemment j'y arrive pas, une dernière run avec azazel où j'ai battu satan avant de me rendre compte que j'étais en normal...", status: "en cours" },
{ d: "2026-08-16", t: "anime", title: "Dai Mahou Touge", img: "anime/daimahoutouge.jpg", note: "normal episode, 1/4", status: "en cours" },
{ d: "2026-08-17", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "que des runs avec azazel parce que je veux m'amuser et évidemment que des wins, j'ai enfin battu satan 5 fois, prochaine étape battre isaac 4 fois de plus !", status: "en cours" },
{ d: "2026-08-17", t: "anime", title: "Dai Mahou Touge", img: "anime/daimahoutouge.jpg", note: "normal episode, 2/4", status: "en cours" },
{ d: "2026-08-17", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "une run après le taf avec azazel, j'ai battu isaac", status: "en cours" },
{ d: "2026-08-17", t: "musique", title: "444 nuits", img: "music/444.webp", note: "première écoute" },
{ d: "2026-08-17", t: "musique", title: "445e nuit", img: "music/445.webp", note: "première écoute" },
{ d: "2026-08-18", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "deux runs trop bien avec que des items quality 4 et 3, j'ai battu hush pour la première fois, fais le boss rush pour la première fois aussi et battu isaac une autre fois également, je me suis amusé comme un petit fou", status: "en cours" },
{ d: "2026-08-18", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "deux runs de merde, aucune luck, ça m'apprendra à commencer avec des items de merde", status: "en cours" },
{ d: "2026-08-19", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "deux runs, deux wins, j'ai enfin battu isaac 5 fois ! prochaine étape blue baby !", status: "en cours" },
{ d: "2026-08-19", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "2L", status: "en cours" },
{ d: "2026-08-20", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "une run où j'ai battu pour la première fois blue baby et delirium", status: "en cours" },
{ d: "2026-08-20", t: "musique", title: "Cheddar", img: "music/cheddar.webp", note: "réécoute" },
{ d: "2026-08-20", t: "musique", title: "Coach K", img: "music/coachk.webp", note: "première écoute" },
{ d: "2026-08-20", t: "musique", title: "Même Vie", img: "music/memevie.webp", note: "première écoute" },
{ d: "2026-08-20", t: "musique", title: "KKSHISENSE8", img: "music/kks.webp", note: "première écoute" },
{ d: "2026-08-20", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "deux runs après le taf, une abominable et une seconde où j'ai littéralement fait une god run, ma meilleure, où j'ai eu l'effet du super mush tous les étages grâce à un item glich récupéré plus tot (la pioche), j'ai donc battu the lamb pour la première fois", status: "en cours" },
{ d: "2026-08-21", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "2L/2W", status: "en cours" },
{ d: "2026-08-21", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1191/?", status: "en cours" },
{ d: "2026-08-21", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "petite game d'isaac où j'ai battu the lamb encore une fois", status: "en cours" },
{ d: "2026-08-22", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "très bonne session, j'ai battu deux fois mega satan pour la première fois et j'ai battu hush deux fois de plus pour débloquer le nouveau chemin, prochain objectif, mother !", status: "en cours" },
{ d: "2026-08-22", t: "musique", title: "Benji", img: "music/benji.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "Dans le Fond", img: "music/danslefond.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "Là-bas", img: "music/labas.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "Abras (10 Bands Freestyle)", img: "music/abras.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "66 Mesures", img: "music/66.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "Fugu", img: "music/fugu.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "James Worthy", img: "music/jamesworthy.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "Baby Milo", img: "music/babymilo.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "Ibiki", img: "music/ibiki.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "16par16", img: "music/seize.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "16par16 Remix", img: "music/seizer.webp", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "Grandmaster Splinter", img: "music/grandmaster.jpg", note: "première écoute" },
{ d: "2026-08-22", t: "musique", title: "Adios Bahamas", img: "music/adiosbahamas.webp", note: "réécoute" },
{ d: "2026-08-22", t: "jeu", title: "Valorant", img: "games/valorant.png", note: "quelques deathmatchs", status: "en cours" },
{ d: "2026-08-23", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "nothing to say", status: "en cours" },
{ d: "2026-08-23", t: "anime", title: "Saihate ni Hana", img: "anime/saihate.jpg", note: "music" },
{ d: "2026-08-23", t: "anime", title: "My Love", img: "anime/mylove.jpg", note: "music" },
{ d: "2026-08-23", t: "anime", title: "Kyapi", img: "anime/kyapi.jpg", note: "music" },
{ d: "2026-08-23", t: "anime", title: "Fate/Grand Order: Hoshimi no Kairou", img: "anime/fatehoshimi.jpg", note: "short" },
{ d: "2026-08-23", t: "anime", title: "Hitotsu ni Naru Koe", img: "anime/hitotsu.jpg", note: "music" },
{ d: "2026-08-23", t: "anime", title: "Kagami yo Kagami", img: "anime/kagami.jpg", note: "music" },
{ d: "2026-08-23", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "très bonne session, j'ai battu mother pour la première fois et greed deux fois pour la première fois aussi", status: "en cours" },
{ d: "2026-08-23", t: "anime", title: "Sanzen Nenshou", img: "anime/sanzen.jpg", note: "music" },
{ d: "2026-08-23", t: "anime", title: "Yogsimmanh-eun Dwaeji", img: "anime/yogsimmanh.jpg", note: "short" },
{ d: "2026-08-23", t: "anime", title: "Garou Densetsu: CotW - Monogatari wa, Ji no Shou e", img: "anime/garoudensetsu.jpg", note: "short" },
{ d: "2026-08-23", t: "anime", title: "Shen Ming Fang Song Zhong", img: "anime/shenming.jpg", note: "short" },
{ d: "2026-08-23", t: "anime", title: "Sougen no Kagayaki CM", img: "anime/sougen.jpg", note: "commercial" },
{ d: "2026-08-23", t: "anime", title: "Garakuta Road", img: "anime/garakuta.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Freaky Deaky Love", img: "anime/freakydeaky.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Nee, Icchau yo.", img: "anime/neeicchau.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Eikyuu ni Karenu Hana", img: "anime/eikyuu.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Gedoku Funou Datta", img: "anime/gedoku.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "C kara Hajimaru ABC", img: "anime/abc.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Angry Rabbit", img: "anime/angryrabbit.jpg", note: "short" },
{ d: "2026-08-24", t: "anime", title: "Sushi★Sushi★Daisushi", img: "anime/daisushi.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Ultra Tamashii", img: "anime/ultratamashii.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Never Gonna Give You Up", img: "anime/giveyouup.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Campus Mode!!", img: "anime/campusmode.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Oshiri Puri Ondo", img: "anime/oshiripuri.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Nalsum", img: "anime/nalsum.jpg", note: "short" },
{ d: "2026-08-24", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "plusieurs runs avec blue baby et c'était à chier, je hais ce personnage", status: "en cours" },
{ d: "2026-08-24", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "nouvelle session, j'ai enfin débloqué le dé pour isaac", status: "en cours" },
{ d: "2026-08-24", t: "anime", title: "Changga-ui Jageun Teotbat", img: "anime/changga.jpg", note: "short" },
{ d: "2026-08-24", t: "anime", title: "Super ni Tojikomerareta Bokura", img: "anime/supernitoji.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Continue", img: "anime/continue.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "I Found Me", img: "anime/ifoundme.jpg", note: "music" },
{ d: "2026-08-24", t: "anime", title: "Dai Mahou Touge", img: "anime/daimahoutouge.jpg", note: "normal episode, 3/4", status: "en cours" },
{ d: "2026-08-25", t: "musique", title: "You Won't Go Before You're Supposed To", img: "music/youwontgo.webp", note: "première écoute, excellente surprise, ce n'est pas un style que j'écoute habituellement mais j'ai adoré" },
{ d: "2026-08-25", t: "musique", title: "RTJ4", img: "music/rtj.webp", note: "première écoute, j'y arrive pas, y a quelque chose de cheesy dans l'album" },
{ d: "2026-08-25", t: "anime", title: "Dai Mahou Touge", img: "anime/daimahoutouge.jpg", note: "normal episode, 4/4" },
{ d: "2026-08-25", t: "anime", title: "Dai Mahou Touge Omake", img: "anime/daimahoutougeomake.jpg", note: "short episode, 4/4" },
{ d: "2026-08-25", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "nouvelle session, pas dingue mais j'ai quand même battu isaac et blue baby avec isaac et je me suis bien amusé sur le mode greed avec des synergies bien pétées", status: "en cours" },
{ d: "2026-08-25", t: "film", title: "Déjà le sang de mai ensemençait novembre", img: "films/mainovembre.jpg", note: "documentaire, d'utilité publique" },
{ d: "2026-08-26", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "challenges 8 et 16 faits !", status: "en cours" },
{ d: "2026-08-26", t: "jeu", title: "The Binding of Isaac: Repentance", img: "games/isaac.jpg", note: "", status: "en cours" },
{ d: "2026-08-26", t: "musique", title: "Getz / Gilberto", img: "music/getz.webp", note: "réécoute, chef-d'oeuvre" },
{ d: "2026-08-26", t: "manga", title: "Furyou Taimashi Reina", img: "manga/reina.jpg", note: "10/78", status: "en cours" },
];