// ── JOURNAL & CALENDRIER ──
const journalData = [
{ d: "2026-04-19", t: "livre", title: "Le Bouffon", img: "covers/lebouffon.jpg", note: "lu en entier" },
{ d: "2026-04-19", t: "film", title: "Sonatine - Mélodie mortelle", img: "films/sonatine.webp", note: "" },
{ d: "2026-04-19", t: "anime", title: "Choro Mesu Days", img: "anime/choromesudays.jpg", note: "épisode 1", blur: true },
{ d: "2026-04-20", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "épisode 3" },
{ d: "2026-04-20", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "épisode 1" },
{ d: "2026-04-21", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "épisode 2" },
{ d: "2026-04-21", t: "anime", title: "Dead or Love", img: "anime/deadorlove.jpg", note: "music" },
{ d: "2026-04-22", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "épisode 3" },
{ d: "2026-04-22", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "commencé le livre, 10 pages" },
{ d: "2026-04-23", t: "musique", title: "Safety in the Sun", img: "music/safetyinthesun.webp", note: "Sea of Dreams est de loin le meilleur son" },
{ d: "2026-04-23", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "chapitre 1181" },
{ d: "2026-04-23", t: "anime", title: "Oshikake! Bakunyuu Gal Harem Seikatsu", img: "anime/oshikake.jpg", note: "2 épisodes", blur: true },
{ d: "2026-04-23", t: "musique", title: "Half Blood (BloodLuxe)", img: "music/halfblood.webp", note: "Flashout Freestyle >" },
{ d: "2026-04-24", t: "anime", title: "Be My Star", img: "anime/bemystar.jpg", note: "" },
{ d: "2026-04-24", t: "musique", title: "Tristesse Business : Saison 1", img: "music/tristessebusiness.webp", note: "réécoute" },
{ d: "2026-04-24", t: "musique", title: "YAMOTO", img: "music/yamoto.webp", note: "réécoute" },
{ d: "2026-04-25", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "épisode 1" },
{ d: "2026-04-26", t: "musique", title: "Luv(sic) Hexalogy", img: "music/luvsichexalogy.webp", note: "réécoute" },
{ d: "2026-04-26", t: "anime", title: "You & Aizu", img: "anime/youaizu.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Hanaikada", img: "anime/hanaikada.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Dengeki", img: "anime/dengeki.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "HoYoHoYo ni Shite Ageru♪", img: "anime/hoyohoyo.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Cha Cha Cha feat. G-Dragon", img: "anime/chachacha.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Move On", img: "anime/moveon.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Kaze no Anthem", img: "anime/kazenoanthem.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Bakumei Diver!!!!", img: "anime/bakumeidriver.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Malhae Yes Or No", img: "anime/malhae.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Mouth Music feat. Takkyu Ishino, Shinco", img: "anime/mouthmusic.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Cupcake feat. punchnello", img: "anime/cupcake.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Seoul Phonk feat. Skyminhyuk", img: "anime/seoulphonk.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "épisode 4" },
{ d: "2026-04-26", t: "musique", title: "Just Friends", img: "music/justfriends.webp", note: "réécoute" },
{ d: "2026-04-26", t: "anime", title: "Adrenaline (NO1 Ver.)", img: "anime/adrenaline.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Ichi Ni no San", img: "anime/ichininosan.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Judgement?", img: "anime/judgement.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Side Quest King (KISAI remix)", img: "anime/sidequestking.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "épisodes 2 & 3" },
{ d: "2026-04-27", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "lecture de 16 pages" },
{ d: "2026-04-28", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "épisodes 4 & 5" },
{ d: "2026-04-28", t: "musique", title: "Kekra", img: "music/kekra.webp", note: "réécoute" },
{ d: "2026-04-28", t: "musique", title: "spleen. social club", img: "music/spleensocialclub.PNG", note: "première écoute" },
{ d: "2026-04-29", t: "musique", title: "Extasia", img: "music/extasia.webp", note: "première écoute" },
{ d: "2026-04-30", t: "anime", title: "Jyuugoya", img: "anime/jyuugoya.jpg", note: "music" },
{ d: "2026-04-30", t: "anime", title: "Fact Check (Bulgasaui) (2Spade Remix)", img: "anime/factcheck.jpg", note: "music" },
{ d: "2026-04-30", t: "anime", title: "Lazy River", img: "anime/lazyriver.jpg", note: "music" },
{ d: "2026-05-01", t: "musique", title: "Tamara", img: "music/tamara.webp", note: "première écoute" },
{ d: "2026-05-02", t: "anime", title: "Rave In My Ears", img: "anime/raveinmyears.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Lanternoid", img: "anime/lanternoid.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Kira", img: "anime/kira.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Mirai no Lemon Sour x Final Fantasy VII Rebirth CM", img: "anime/mirainolemon.jpg", note: "commercial" },
{ d: "2026-05-02", t: "anime", title: "Uta no Uta (2026)", img: "anime/utanouta2026.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Re:Prism", img: "anime/reprism.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Jujutsu Kaisen Modulo Saishuu Sankan Hatsubai Kinen Special PV", img: "anime/jujutsukaisenmodulo.jpg", note: "short" },
{ d: "2026-05-02", t: "anime", title: "Flipper (2026)", img: "anime/flipper2026.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Girl feat. kojikoji", img: "anime/girlfeatkoji.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Sumikko Style Cafe Base Rap Compilation", img: "anime/sumikko.jpg", note: "commercial" },
{ d: "2026-05-02", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "épisode 4" },
{ d: "2026-05-02", t: "anime", title: "Bousai Keihatsu Douga", img: "anime/bousaikeihatsu.jpg", note: "short" },
{ d: "2026-05-02", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "70/126" },
{ d: "2026-05-03", t: "anime", title: "Broots", img: "anime/broots.jpg", note: "short" },
{ d: "2026-05-03", t: "anime", title: "Eguo", img: "anime/eguo.jpg", note: "short" },
{ d: "2026-05-03", t: "série", title: "One Piece", img: "series/onepiecesaison2.jpg", note: "saison 2 épisode 4" },
{ d: "2026-05-03", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "épisode 5" },
{ d: "2026-05-04", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "100/126" },
];