// ── JOURNAL & CALENDRIER ──
const journalData = [
{ d: "2026-04-19", t: "livre", title: "Le Bouffon", img: "covers/lebouffon.jpg", note: "lu en entier" },
{ d: "2026-04-19", t: "film", title: "Sonatine - Mélodie mortelle", img: "films/sonatine.webp", note: "premier film du réal que je regarde" },
{ d: "2026-04-19", t: "anime", title: "Choro Mesu Days", img: "anime/choromesudays.jpg", note: "hentai, 1/?", blur: true, status: "en cours" },
{ d: "2026-04-20", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 3/12", status: "en cours" },
{ d: "2026-04-20", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 1/12", status: "en cours" },
{ d: "2026-04-21", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 2/12", status: "en cours" },
{ d: "2026-04-21", t: "anime", title: "Dead or Love", img: "anime/deadorlove.jpg", note: "music" },
{ d: "2026-04-22", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 3/12", status: "en cours" },
{ d: "2026-04-22", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "commencé le livre, 10 pages", status: "en cours" },
{ d: "2026-04-23", t: "musique", title: "Safety in the Sun", img: "music/safetyinthesun.webp", note: "Sea of Dreams est de loin le meilleur son" },
{ d: "2026-04-23", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1181/?", status: "en cours" },
{ d: "2026-04-23", t: "anime", title: "Oshikake! Bakunyuu Gal Harem Seikatsu", img: "anime/oshikake.jpg", note: "hentai, 2/?", blur: true, status: "en cours" },
{ d: "2026-04-23", t: "musique", title: "Half Blood (BloodLuxe)", img: "music/halfblood.webp", note: "Flashout Freestyle >" },
{ d: "2026-04-24", t: "anime", title: "Be My Star", img: "anime/bemystar.jpg", note: "music" },
{ d: "2026-04-24", t: "musique", title: "Tristesse Business : Saison 1", img: "music/tristessebusiness.webp", note: "réécoute" },
{ d: "2026-04-24", t: "musique", title: "YAMOTO", img: "music/yamoto.webp", note: "réécoute" },
{ d: "2026-04-25", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 1/13", status: "en cours" },
{ d: "2026-04-26", t: "musique", title: "Luv(sic) Hexalogy", img: "music/luvsichexalogy.webp", note: "réécoute" },
{ d: "2026-04-26", t: "anime", title: "You & Aizu", img: "anime/youaizu.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Hanaikada", img: "anime/hanaikada.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Dengeki", img: "anime/dengeki.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "HoYoHoYo ni Shite Ageru♪", img: "anime/hoyohoyo.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Cha Cha Cha feat. G-Dragon", img: "anime/chachacha.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Move On", img: "anime/moveon.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Kaze no Anthem", img: "anime/kazenoanthem.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Bakumei Diver!!!!", img: "anime/bakumeidriver.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Malhae Yes Or No", img: "anime/malhae.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Mouth Music feat. Takkyu Ishino, Shinco", img: "anime/mouthmusic.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Cupcake feat. punchnello", img: "anime/cupcake.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Seoul Phonk feat. Skyminhyuk", img: "anime/seoulphonk.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 4/12", status: "en cours" },
{ d: "2026-04-26", t: "musique", title: "Just Friends", img: "music/justfriends.webp", note: "réécoute" },
{ d: "2026-04-26", t: "anime", title: "Adrenaline (NO1 Ver.)", img: "anime/adrenaline.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Ichi Ni no San", img: "anime/ichininosan.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Judgement?", img: "anime/judgement.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Side Quest King (KISAI remix)", img: "anime/sidequestking.jpg", note: "music" },
{ d: "2026-04-26", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 2-3/13", status: "en cours" },
{ d: "2026-04-27", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "lecture de 16 pages", status: "en cours" },
{ d: "2026-04-28", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 4-5/13", status: "en cours" },
{ d: "2026-04-28", t: "musique", title: "Kekra", img: "music/kekra.webp", note: "réécoute" },
{ d: "2026-04-28", t: "musique", title: "spleen. social club", img: "music/spleensocialclub.PNG", note: "première écoute" },
{ d: "2026-04-29", t: "musique", title: "Extasia", img: "music/extasia.webp", note: "première écoute" },
{ d: "2026-04-30", t: "anime", title: "Jyuugoya", img: "anime/jyuugoya.jpg", note: "music" },
{ d: "2026-04-30", t: "anime", title: "Fact Check (Bulgasaui) (2Spade Remix)", img: "anime/factcheck.jpg", note: "music" },
{ d: "2026-04-30", t: "anime", title: "Lazy River", img: "anime/lazyriver.jpg", note: "music" },
{ d: "2026-05-01", t: "musique", title: "Tamara", img: "music/tamara.webp", note: "première écoute" },
{ d: "2026-05-02", t: "anime", title: "Rave In My Ears", img: "anime/raveinmyears.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Lanternoid", img: "anime/lanternoid.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Kira", img: "anime/kira.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Mirai no Lemon Sour x Final Fantasy VII Rebirth CM", img: "anime/mirainolemon.jpg", note: "commercial" },
{ d: "2026-05-02", t: "anime", title: "Uta no Uta (2026)", img: "anime/utanouta2026.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Re:Prism", img: "anime/reprism.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Jujutsu Kaisen Modulo Saishuu Sankan Hatsubai Kinen Special PV", img: "anime/jujutsukaisenmodulo.jpg", note: "short" },
{ d: "2026-05-02", t: "anime", title: "Flipper (2026)", img: "anime/flipper2026.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Girl feat. kojikoji", img: "anime/girlfeatkoji.jpg", note: "music" },
{ d: "2026-05-02", t: "anime", title: "Sumikko Style Cafe Base Rap Compilation", img: "anime/sumikko.jpg", note: "commercial" },
{ d: "2026-05-02", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 4/12", status: "en cours" },
{ d: "2026-05-02", t: "anime", title: "Bousai Keihatsu Douga", img: "anime/bousaikeihatsu.jpg", note: "short" },
{ d: "2026-05-02", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "70/126", status: "en cours" },
{ d: "2026-05-03", t: "anime", title: "Broots", img: "anime/broots.jpg", note: "short" },
{ d: "2026-05-03", t: "anime", title: "Eguo", img: "anime/eguo.jpg", note: "short" },
{ d: "2026-05-03", t: "série", title: "One Piece", img: "series/onepiecesaison2.jpg", note: "saison 2 - 4/8", status: "en cours" },
{ d: "2026-05-03", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 5/12", status: "en cours" },
{ d: "2026-05-04", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "100/126", status: "en cours" },
{ d: "2026-05-05", t: "livre", title: "Libertés sans expression", img: "covers/libertesansexpression.jpg", note: "terminé" },
{ d: "2026-05-05", t: "anime", title: "Sigan Yeokhaeng", img: "anime/siganyeokhaeng.jpg", note: "music" },
{ d: "2026-05-05", t: "anime", title: "Dance at the Moonlight feat. kojikoji", img: "anime/danceatthemoonlight.jpg", note: "music" },
{ d: "2026-05-05", t: "anime", title: "Hoyahoyaraa", img: "anime/hoyahoyaraa.jpg", note: "music" },
{ d: "2026-05-06", t: "anime", title: "Toge", img: "anime/toge.jpg", note: "music" },
{ d: "2026-05-06", t: "anime", title: "Bakusoku Ronriness", img: "anime/bakusokuronriness.jpg", note: "music" },
{ d: "2026-05-06", t: "anime", title: "Mind Scape", img: "anime/mindscape.jpg", note: "short" },
{ d: "2026-05-06", t: "anime", title: "Madoromi no Shuumatsu", img: "anime/madorominoshuumatsu.jpg", note: "short" },
{ d: "2026-05-06", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 6/13", status: "en cours" },
{ d: "2026-05-07", t: "anime", title: "Mr. Shape", img: "anime/mrshape.jpg", note: "short episode, 4/4" },
{ d: "2026-05-07", t: "anime", title: "Parking Area", img: "anime/parkingarea.jpg", note: "short" },
{ d: "2026-05-08", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1182/?", status: "en cours" },
{ d: "2026-05-09", t: "anime", title: "Haru wo Irodoru", img: "anime/haruwoirodoru.jpg", note: "short" },
{ d: "2026-05-09", t: "anime", title: "Chichin Pui Pui", img: "anime/chichinpuipui.jpg", note: "music" },
{ d: "2026-05-09", t: "anime", title: "Chiikawa Park TV CMs", img: "anime/chiikawaparkcms.jpg", note: "commercial" },
{ d: "2026-05-09", t: "anime", title: "Hifukidake", img: "anime/hifukidake.jpg", note: "short" },
{ d: "2026-05-09", t: "anime", title: "Jiu Wo", img: "anime/jiuwo.jpg", note: "short" },
{ d: "2026-05-09", t: "anime", title: "Koi no Tamashii", img: "anime/koinotamashii.jpg", note: "music" },
{ d: "2026-05-09", t: "anime", title: "Star Trail", img: "anime/startrail.jpg", note: "music" },
{ d: "2026-05-09", t: "anime", title: "NaN Game", img: "anime/nangame.jpg", note: "music" },
{ d: "2026-05-10", t: "anime", title: "Kudamonou", img: "anime/kudamonou.jpg", note: "short episode, 3/3" },
{ d: "2026-05-10", t: "anime", title: "Sweet Singapore CMs", img: "anime/sweetsingaporecms.jpg", note: "commercial" },
{ d: "2026-05-10", t: "anime", title: "Poke Oki", img: "anime/pokeoki.jpg", note: "short" },
{ d: "2026-05-10", t: "anime", title: "Konohakaseki no Natsu", img: "anime/konohakaseki.jpg", note: "short film" },
{ d: "2026-05-10", t: "anime", title: "Kujira wo Yumemu", img: "anime/kujirawoyumeru.jpg", note: "short" },
{ d: "2026-05-10", t: "anime", title: "I Got feat. Woodie Gochild", img: "anime/igotwoodie.jpg", note: "music" },
{ d: "2026-05-10", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 6/12", status: "en cours" },
{ d: "2026-05-10", t: "anime", title: "Mangzhong", img: "anime/mangzhong.jpg", note: "short film" },
{ d: "2026-05-12", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 5/12", status: "en cours" },
{ d: "2026-05-12", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 7/13", status: "en cours" },
{ d: "2026-05-14", t: "anime", title: "Kin no Ono, Gin no Ono, Emerald no Ono", img: "anime/kinnoonogin.jpg", note: "music" },
{ d: "2026-05-14", t: "musique", title: "Circles", img: "music/circles.webp", note: "réécoute" },
{ d: "2026-05-15", t: "anime", title: "Marriagetoxin", img: "anime/marriagetoxin.jpg", note: "normal episode, 6/12", status: "en cours" },
{ d: "2026-05-16", t: "musique", title: "Iceman", img: "music/iceman.webp", note: "première écoute, ennuyeux à mourir" },
{ d: "2026-05-16", t: "musique", title: "Maid of Honour", img: "music/maidofhonour.webp", note: "première écoute, nul" },
{ d: "2026-05-16", t: "musique", title: "Habibti", img: "music/habibti.webp", note: "première écoute, nul" },
{ d: "2026-05-16", t: "anime", title: "Kick-Heart", img: "anime/kick-heart.jpg", note: "short film" },
{ d: "2026-05-17", t: "film", title: "Junk Head", img: "films/junkhead.webp", note: "une vibe à la blame" },
{ d: "2026-05-17", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 7/12, l'anime est vraiment bien, top 3 persos : Yasuaki Kaku, Mitsuhide Ryuumon, Gou Sugou", status: "en cours" },
{ d: "2026-05-18", t: "manga", title: "Tower Dungeon", img: "manga/towerdungeon.jpg", note: "premier tome de lu, très bon début, j'adore l'ambiance", status: "en cours" },
{ d: "2026-05-18", t: "musique", title: "Pluie, montagnes et soleil", img: "music/pluiemontagnessoleil.webp", note: "première écoute même si je connaissais déjà quelques sons" },
{ d: "2026-05-18", t: "film", title: "Mad God", img: "films/madgod.webp", note: "fascinant" },
{ d: "2026-05-20", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 8/13", status: "en cours" },
{ d: "2026-05-21", t: "série", title: "One Piece", img: "series/onepiecesaison2.jpg", note: "saison 2 - 5/8", status: "en cours" },
{ d: "2026-05-21", t: "musique", title: "Balloonerism", img: "music/balloonerism.webp", note: "première écoute, album sympa, le meiller son est funny papers pour moi" },
{ d: "2026-05-21", t: "manga", title: "Tower Dungeon", img: "manga/towerdungeon.jpg", note: "second tome de lu", status: "en cours" },
{ d: "2026-05-21", t: "musique", title: "キャット", img: "music/キャット.webp", note: "première écoute" },
{ d: "2026-05-22", t: "anime", title: "Numb Numb feat. Hatsune Miku, Kasane Teto", img: "anime/numbnumb.jpg", note: "music" },
{ d: "2026-05-23", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1183/?", status: "en cours" },
{ d: "2026-05-23", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 1/24", status: "en cours" },
{ d: "2026-05-24", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 2-3-4/24", status: "en cours" },
{ d: "2026-05-24", t: "musique", title: "Ateyaba", img: "music/ateyaba.webp", note: "première écoute, je connaissais déjà Venus" },
{ d: "2026-05-24", t: "anime", title: "Bite (2024)", img: "anime/bite.jpg", note: "music" },
{ d: "2026-05-24", t: "anime", title: "Mofumofu Man", img: "anime/mofumofuman.jpg", note: "short" },
{ d: "2026-05-24", t: "anime", title: "Rakuraku Fukuyaku Jelly: Oshaberi na Ningen no Tame ni", img: "anime/rakurakufukuyaku.jpg", note: "commercial" },
{ d: "2026-05-24", t: "anime", title: "Tokyo Night Dreaming feat. No Rome", img: "anime/tokyonightdreaming.jpg", note: "music" },
{ d: "2026-05-24", t: "anime", title: "Expressions", img: "anime/expressions.jpg", note: "music" },
{ d: "2026-05-24", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 8/12", status: "en cours" },
{ d: "2026-05-24", t: "musique", title: "Keitaidenwa", img: "music/keitaidenwa.webp", note: "première écoute, je connaissais déjà Hyperventilation" },
{ d: "2026-05-24", t: "jeu", title: "Slime Rancher", img: "games/slimerancher.jpg", note: "94 minutes", status: "en cours" },
{ d: "2026-05-24", t: "anime", title: "Chimimonryou", img: "anime/chimimonryou.jpg", note: "hentai, 1/?", blur: true, status: "en cours" },
{ d: "2026-05-26", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 9/13", status: "en cours" },
{ d: "2026-05-27", t: "musique", title: "Brat", img: "music/brat.webp", note: "première écoute, je sors de ma zone de confort et c'est vraiment pas mal" },
{ d: "2026-05-27", t: "anime", title: "Airman ga Taosenai Team.Nekokan [Neko] Premium Version", img: "anime/airmangataosenai.jpg", note: "commercial" },
{ d: "2026-05-27", t: "jeu", title: "Slime Rancher", img: "games/slimerancher.jpg", note: "27 minutes", status: "en cours" },
{ d: "2026-05-27", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 5/24", status: "en cours" },
{ d: "2026-05-28", t: "film", title: "Cure", img: "films/cure.jpg", note: "pas convaincu" },
{ d: "2026-05-29", t: "livre", title: "Morphine", img: "covers/morphine.jpg", note: "lu dans le train vers Paris" },
{ d: "2026-05-30", t: "livre", title: "Le Nez", img: "covers/lenez.jpg", note: "lu dans le train vers Nice" },
{ d: "2026-05-31", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1184/?", status: "en cours" },
{ d: "2026-06-01", t: "musique", title: "Heroes & Villains", img: "music/heroesvillains.webp", note: "réécoute, un album toujours aussi exceptionnel" },
{ d: "2026-06-03", t: "musique", title: "Disco Inferno", img: "music/discoinferno.webp", note: "première écoute, bon petit délire, bonne vibe" },
{ d: "2026-06-03", t: "musique", title: "PUBLIC ENEMY", img: "music/publicenemy.jpg", note: "première écoute, ça s'écoute sans plus" },
{ d: "2026-06-03", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 9/12", status: "en cours" },
{ d: "2026-06-04", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 10/13", status: "en cours" },
{ d: "2026-06-04", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "1h30 à peu près sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-05", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 6-7/24", status: "en cours" },
{ d: "2026-06-06", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 8-9/24", status: "en cours" },
{ d: "2026-06-06", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "3h sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-07", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 10-16/24", status: "en cours" },
{ d: "2026-06-07", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "2h22 sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-08", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 17-19/24", status: "en cours" },
{ d: "2026-06-09", t: "anime", title: "Vinland Saga", img: "anime/vinlandsaga.jpg", note: "normal episode, 20-24/24" },
{ d: "2026-06-11", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 10/12", status: "en cours" },
{ d: "2026-06-12", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1185/?", status: "en cours" },
{ d: "2026-06-12", t: "anime", title: "Shinkirou", img: "anime/shinkirou.jpg", note: "music" },
{ d: "2026-06-13", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 11/13", status: "en cours" },
{ d: "2026-06-13", t: "musique", title: "Ivy League", img: "music/ivyleague.webp", note: "réécoute, les musiques ivy league et for what à jamais dans mon coeur..." },
{ d: "2026-06-13", t: "anime", title: "Bunch 25-shuunen Kinen Special PV: Gokushufudou", img: "anime/bunch25.jpg", note: "short" },
{ d: "2026-06-13", t: "anime", title: "Akane", img: "anime/akane.jpg", note: "music" },
{ d: "2026-06-13", t: "anime", title: "Torimodosou, Ichiban Taisetsu na Mono wo: GIST Project", img: "anime/torimodosou.jpg", note: "commercial" },
{ d: "2026-06-13", t: "anime", title: "Cin Sai Syu", img: "anime/cinsaisyu.jpg", note: "music" },
{ d: "2026-06-13", t: "anime", title: "No Thank Cute!", img: "anime/nothankcute.jpg", note: "music" },
{ d: "2026-06-13", t: "anime", title: "Vision Megane CMs", img: "anime/visionmegane.jpg", note: "commercial" },
{ d: "2026-06-13", t: "anime", title: "Mebae feat. Phoka", img: "anime/mebae.jpg", note: "music" },
{ d: "2026-06-13", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "2h18 sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-14", t: "jeu", title: "Fears to Fathom: Scratch Creek", img: "games/fearstofathom.jpg", note: "jeu terminé en 2,7 heures, en une session, pas convaincu" },
{ d: "2026-06-15", t: "anime", title: "Heart Mark Oome", img: "anime/heartmarkoome.jpg", note: "hentai, 2/?", blur: true, status: "en cours" },
{ d: "2026-06-16", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 12/13", status: "en cours" },
{ d: "2026-06-16", t: "anime", title: "Rocket Science", img: "anime/rocketscience.jpg", note: "music" },
{ d: "2026-06-16", t: "anime", title: "Petals", img: "anime/petals.jpg", note: "music" },
{ d: "2026-06-16", t: "anime", title: "Free To Go", img: "anime/freetogo.jpg", note: "music" },
{ d: "2026-06-16", t: "anime", title: "Aisarenakutemo Kimi ga Iru feat. Hatsune Miku", img: "anime/aisarenakutemo.jpg", note: "music" },
{ d: "2026-06-16", t: "anime", title: "Red Table", img: "anime/redtable.jpg", note: "short" },
{ d: "2026-06-17", t: "anime", title: "Desk Bugs", img: "anime/deskbugs.jpg", note: "short" },
{ d: "2026-06-17", t: "anime", title: "Lakenaria no Yume", img: "anime/lakenaria.jpg", note: "music" },
{ d: "2026-06-17", t: "anime", title: "Muu", img: "anime/muu.jpg", note: "music" },
{ d: "2026-06-17", t: "anime", title: "Tarepanda (ONA)", img: "anime/tarepanda.jpg", note: "short" },
{ d: "2026-06-17", t: "anime", title: "Chocopa", img: "anime/chocopa.jpg", note: "short" },
{ d: "2026-06-17", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "3h07 sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-18", t: "film", title: "Backrooms", img: "films/backrooms.jpg", note: "je l'ai regardé au cinéma, un peu déçu pour être honnête" },
{ d: "2026-06-19", t: "anime", title: "Reika wa Karei na Boku no Joou The Animation", img: "anime/reika.jpg", note: "hentai, 1/?", blur: true, status: "en cours" },
{ d: "2026-06-20", t: "anime", title: "Play", img: "anime/play.jpg", note: "music" },
{ d: "2026-06-21", t: "anime", title: "Kamisama Hajimemashita (Music)", img: "anime/kamisama.jpg", note: "music" },
{ d: "2026-06-21", t: "anime", title: "Himitsu Doushi", img: "anime/himitsudoushi.jpg", note: "short" },
{ d: "2026-06-21", t: "anime", title: "MAPPA 15th Anniversary Movie: Seikatsu", img: "anime/mappa15.jpg", note: "short" },
{ d: "2026-06-21", t: "manga", title: "Shouwaru Gal Shitsukerareru", img: "manga/shouwarugal.jpg", note: "hentai, 1/1", blur: true },
{ d: "2026-06-21", t: "anime", title: "Nippon Sangoku", img: "anime/nipponsangoku.jpg", note: "normal episode, 11-12/12, c'était vraiment bien" },
{ d: "2026-06-21", t: "musique", title: "HHHH²", img: "music/hhhh².jpg", note: "première écoute de ce projet surprise, pas nul mais pas exceptionnel non plus, j'ai connu mieux d'un Josman lover" },
{ d: "2026-06-22", t: "anime", title: "The Whole Blue World", img: "anime/wholeblue.jpg", note: "music" },
{ d: "2026-06-24", t: "anime", title: "Tongari Boushi no Atelier", img: "anime/tongari.jpg", note: "normal episode, 13/13" },
{ d: "2026-06-24", t: "anime", title: "Vinland Saga Season 2", img: "anime/vinlandsaga2.jpg", note: "normal episode, 2/24", status: "en cours" },
{ d: "2026-06-25", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "48 minutes sur un serveur mmorpg", status: "en cours" },
{ d: "2026-06-26", t: "film", title: "Prehistoric Beast", img: "films/prehistoricbeast.webp", note: "court-métrage sympa" },
{ d: "2026-06-27", t: "film", title: "MutantLand", img: "films/mutantland.jpg", note: "court-métrage aussi du même réal, en cgi cette fois mais toujours aussi cauchemardesque" },
{ d: "2026-06-27", t: "film", title: "D'une peinture... à l'autre", img: "films/peinturealautre.webp", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-06-27", t: "film", title: "Zig Zag", img: "films/zigzag.jpg", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-06-27", t: "film", title: "Le Vol d'Icare", img: "films/levoldicare.webp", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-06-27", t: "film", title: "Hors-jeu", img: "films/horsjeu.webp", note: "court-métrage de Georges Schwizgebel" },
{ d: "2026-06-27", t: "manga", title: "One Piece", img: "manga/onepiece.jpg", note: "1186/?", status: "en cours" },
{ d: "2026-06-27", t: "anime", title: "Vinland Saga Season 2", img: "anime/vinlandsaga2.jpg", note: "normal episode, 4/24", status: "en cours" },
{ d: "2026-06-27", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "3h20 sur un serveur mmorpg, je suis passé niveau 40", status: "en cours" },
{ d: "2026-06-28", t: "jeu", title: "Minecraft", img: "games/minecraft.jpg", note: "2h11 sur un serveur mmorpg", status: "en cours" },
];